import type { DashboardData } from './computeMetrics'
import type { CoffeeChatRequest } from './types'

const actionQueue: CoffeeChatRequest[] = [
  {
    id: 'CC-2025-104',
    addedDate: '2026-05-18',
    prospectName: 'Alex Chen',
    email: 'alex.chen@uw.edu',
    requestType: 'Current Student',
    contactMethod: 'Zoom',
    responsibleManager: 'Youngpyung Lee',
    assignedAmbassador: null,
    status: 'New Request',
    actionNeeded: 'Assign Ambassador',
    priority: 'High',
    dueDate: '2026-05-20',
  },
  {
    id: 'CC-2025-103',
    addedDate: '2026-05-17',
    prospectName: 'Jordan Kim',
    email: 'j.kim@uw.edu',
    requestType: 'Alumni',
    contactMethod: 'Email',
    responsibleManager: 'Cidney Park',
    assignedAmbassador: 'Sam Rivera',
    status: 'Assigned',
    actionNeeded: 'Send Intro Email',
    priority: 'High',
    dueDate: '2026-05-19',
  },
  {
    id: 'CC-2025-098',
    addedDate: '2026-05-10',
    prospectName: 'Taylor Brooks',
    email: 't.brooks@uw.edu',
    requestType: 'Both',
    contactMethod: 'Phone',
    responsibleManager: 'Youngpyung Lee',
    assignedAmbassador: 'Morgan Lee',
    status: 'Feedback Due',
    actionNeeded: 'Send Feedback Form',
    priority: 'Medium',
    dueDate: '2026-05-17',
  },
  {
    id: 'CC-2025-091',
    addedDate: '2026-04-28',
    prospectName: 'Casey Nguyen',
    email: 'casey.n@uw.edu',
    requestType: 'Current Student',
    contactMethod: 'In-person',
    responsibleManager: 'Cidney Park',
    assignedAmbassador: 'Jamie Park',
    status: 'Overdue',
    actionNeeded: 'Review Overdue Request',
    priority: 'High',
    dueDate: '2026-05-02',
  },
  {
    id: 'CC-2025-087',
    addedDate: '2026-05-05',
    prospectName: 'Riley Adams',
    email: 'r.adams@uw.edu',
    requestType: 'Alumni',
    contactMethod: 'Zoom',
    responsibleManager: 'Youngpyung Lee',
    assignedAmbassador: 'Chris Wu',
    status: 'Feedback Sent',
    actionNeeded: 'Follow Up on Feedback',
    priority: 'Medium',
    dueDate: '2026-05-12',
  },
  {
    id: 'CC-2025-082',
    addedDate: '2026-05-14',
    prospectName: 'Morgan Patel',
    email: 'm.patel@uw.edu',
    requestType: 'Current Student',
    contactMethod: 'Email',
    responsibleManager: 'Youngpyung Lee',
    assignedAmbassador: 'Euphie Zhao',
    status: 'Intro Email Sent',
    actionNeeded: 'No Action Needed',
    priority: 'Low',
    dueDate: null,
  },
  {
    id: 'CC-2025-079',
    addedDate: '2026-05-12',
    prospectName: 'Sam Okafor',
    email: 's.okafor@uw.edu',
    requestType: 'Alumni',
    contactMethod: 'Zoom',
    responsibleManager: 'Cidney Park',
    assignedAmbassador: 'Ryan Wu',
    status: 'Assigned',
    actionNeeded: 'Send Intro Email',
    priority: 'High',
    dueDate: '2026-05-16',
  },
  {
    id: 'CC-2025-076',
    addedDate: '2026-05-08',
    prospectName: 'Priya Sharma',
    email: 'priya.s@uw.edu',
    requestType: 'Both',
    contactMethod: 'Phone',
    responsibleManager: 'Youngpyung Lee',
    assignedAmbassador: 'Dominick Mendoza',
    status: 'Feedback Due',
    actionNeeded: 'Send Feedback Form',
    priority: 'Medium',
    dueDate: '2026-05-15',
  },
]

export const demoDashboardData: DashboardData = {
  requests: actionQueue,
  rawCount: 106,
  kpiSummary: {
    totalRequests: 106,
    newRequests: 11,
    needIntroEmail: 18,
    feedbackDue: 12,
    overdue: 7,
    completed: 58,
    introEmailsSent: 84,
    feedbackSentNotReceived: 9,
  },
  actionQueue: actionQueue.filter((r) => r.actionNeeded !== 'No Action Needed'),
  requestTypeBreakdown: [
    { name: 'Current Student', value: 48, color: '#3B6FF5' },
    { name: 'Alumni', value: 35, color: '#8B5CF6' },
    { name: 'Both', value: 23, color: '#F97316' },
  ],
  contactMethodBreakdown: [
    { name: 'Email', value: 42, color: '#3B6FF5' },
    { name: 'Zoom', value: 38, color: '#8B5CF6' },
    { name: 'Phone', value: 15, color: '#22C55E' },
    { name: 'In-person', value: 11, color: '#F59E0B' },
  ],
  statusBreakdown: [
    { name: 'Completed', value: 58 },
    { name: 'Intro Email Sent', value: 22 },
    { name: 'Assigned', value: 12 },
    { name: 'New Request', value: 11 },
    { name: 'Feedback Due', value: 12 },
    { name: 'Overdue', value: 7 },
  ],
  requestsOverTime: [
    { month: 'Oct', requests: 6 },
    { month: 'Nov', requests: 9 },
    { month: 'Dec', requests: 14 },
    { month: 'Jan', requests: 11 },
    { month: 'Feb', requests: 16 },
    { month: 'Mar', requests: 18 },
    { month: 'Apr', requests: 17 },
    { month: 'May', requests: 15 },
  ],
  weeklyActivity: [
    { week: 'W1', count: 4 },
    { week: 'W2', count: 7 },
    { week: 'W3', count: 5 },
    { week: 'W4', count: 12 },
    { week: 'W5', count: 9 },
    { week: 'W6', count: 14 },
    { week: 'W7', count: 11 },
    { week: 'W8', count: 18 },
  ],
  ambassadorWorkload: [
    { name: 'Morgan Lee', active: 8, completed: 14, pendingFeedback: 2 },
    { name: 'Euphie Zhao', active: 7, completed: 12, pendingFeedback: 1 },
    { name: 'Ryan Wu', active: 6, completed: 11, pendingFeedback: 3 },
    { name: 'Dominick Mendoza', active: 9, completed: 10, pendingFeedback: 2 },
    { name: 'Jamie Park', active: 5, completed: 9, pendingFeedback: 0 },
    { name: 'Chris Wu', active: 4, completed: 8, pendingFeedback: 1 },
  ],
  feedbackMetrics: {
    completionRate: 72,
    dueToday: 4,
    overdue: 3,
    sentNotReceived: 9,
  },
  introEmailSlaPercent: 89,
  avgDaysToIntroEmail: 1.8,
}
